# parser.py — Extract financial figures directly from EDGAR HTM filings.
# Every extracted value is tagged with its source label and line number.

import re
import os
from bs4 import BeautifulSoup

# ── Dynamic section detection ──────────────────────────────────────────────────

def _find_header(lines: list, marker: str, validator: str,
                 start: int = 0, window: int = 80) -> int:
    """
    Find the real financial statement header (not a TOC reference) by requiring:
    - A line containing `marker` (short line, < 60 chars)
    - `validator` to appear within `window` lines after it
    Returns line index or -1.
    """
    m, v = marker.lower(), validator.lower()
    for i in range(start, len(lines)):
        if m in lines[i].lower() and len(lines[i]) < 60:
            ctx = " ".join(lines[i : i + window]).lower()
            if v in ctx:
                return i
    return -1


def detect_sections(company: str, lines: list) -> dict:
    """
    Dynamically locate income statement, balance sheet, and cash flow statement
    sections within the filing. Returns {section: (start_line, end_line)}.
    """
    if company == "Google":
        # Google filing order: balance sheet → income statement → cash flows
        balance  = _find_header(lines, "CONSOLIDATED BALANCE SHEETS",       "total assets")
        income   = _find_header(lines, "CONSOLIDATED STATEMENTS OF INCOME", "revenues",           start=balance)
        cashflow = _find_header(lines, "CONSOLIDATED STATEMENTS OF CASH FLOWS", "operating activities", start=income)
        return {
            "balance":  (balance,  income),
            "income":   (income,   cashflow),
            "cashflow": (cashflow, cashflow + 400),
        }
    elif company == "Apple":
        # Apple filing order: income statement → balance sheet → cash flows
        balance  = _find_header(lines, "CONSOLIDATED BALANCE SHEETS",           "cash",        window=80)
        cashflow = _find_header(lines, "CONSOLIDATED STATEMENTS OF CASH FLOWS", "depreciation")
        return {
            "income":   (max(0, balance - 500), balance),
            "balance":  (balance,  cashflow),
            "cashflow": (cashflow, cashflow + 400),
        }
    else:  # Microsoft
        # Microsoft filing order: income statement → balance sheet → cash flows
        # Headers are short single words ("BALANCE", "CASH FLOWS S")
        balance  = _find_header(lines, "BALANCE",    "total assets")
        cashflow = _find_header(lines, "CASH FLOWS", "net income",  start=balance)
        return {
            "income":   (max(0, balance - 200), balance),
            "balance":  (balance,  cashflow),
            "cashflow": (cashflow, cashflow + 400),
        }


CONFIGS = {
    "Apple": {
        "filepath":        "fillings/AppleEDGAR.htm",
        "fiscal_year_end": "September 27, 2025",
        "years":           ["FY2023", "FY2024", "FY2025"],
        "order":           "newest_first",
        "income_labels": {
            "revenue":          ("Total net sales",   ["percentage"]),  # skip "Percentage of total net sales"
            "gross_profit":     ("Total gross margin",[]),
            "operating_income": ("Operating income",  []),
            "net_income":       ("Net income",        []),
        },
        "cashflow_labels": {
            "operating_cf": ("Cash generated by operating activities", []),
            "capex":        ("Payments for acquisition of property, plant and equipment", []),
        },
    },
    "Microsoft": {
        "filepath":        "fillings/MsftEDGAR.htm",
        "fiscal_year_end": "June 30, 2025",
        "years":           ["FY2023", "FY2024", "FY2025"],
        "order":           "newest_first",
        "income_labels": {
            "revenue":          ("Total revenue",    []),
            "gross_profit":     ("Gross margin",     []),
            "operating_income": ("Operating income", []),
            "net_income":       ("Net income",       []),
        },
        "cashflow_labels": {
            "operating_cf": ("Net cash from operations",             []),
            "capex":        ("Additions to property and equipment",  []),
        },
    },
    "Google": {
        "filepath":        "fillings/GoogleEDGAR.htm",
        "fiscal_year_end": "December 31, 2025",
        "years":           ["FY2023", "FY2024", "FY2025"],
        "order":           "oldest_first",
        "income_labels": {
            "revenue":          ("Revenues",          []),
            "cost_of_revenues": ("Cost of revenues",  []),
            "operating_income": ("Income from operations", []),
            "net_income":       ("Net income",        []),
        },
        "cashflow_labels": {
            "operating_cf": ("Net cash provided by operating activities", []),
            "capex":        ("Purchases of property and equipment",       []),
        },
    },
}

# Balance sheet labels (separate because they only give 2 years: FY2024 + FY2025)
BALANCE_LABELS = {
    "Apple": {
        "total_assets":  ("Total assets",             []),
        "current_debt":  ("Term debt",                []),   # first match = current portion
        "lt_debt":       ("Term debt",                []),   # second match = non-current
        "equity":        ("Total shareholders",       []),
    },
    "Microsoft": {
        "total_assets":    ("Total assets",                 []),
        "lt_debt":         ("Long-term debt",               ["current", "portion"]),
        "current_lt_debt": ("Current portion of long-term", []),
        "equity":          ("Total stockholders",           ["liabilities"]),
    },
    "Google": {
        "total_assets": ("Total assets",    []),
        "total_debt":   ("Long-term debt",  []),
        "equity":       ("Total stockholders", ["liabilities"]),
    },
}


# ── Core helpers ───────────────────────────────────────────────────────────────

def load_lines(filepath: str) -> list:
    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        soup = BeautifulSoup(f.read(), "html.parser")
    for tag in soup(["script", "style"]):
        tag.decompose()
    return [l.strip() for l in soup.get_text(separator="\n").splitlines() if l.strip()]


def _is_year(n: int) -> bool:
    return 2000 <= n <= 2035


def find_values(lines: list, label: str, n: int, start: int, end: int,
                exclude_words: list = None, skip_long_lines: bool = True) -> tuple:
    """
    Search lines[start:end] for `label`.
    - Skips lines > 60 chars (catches label appearing mid-sentence in MD&A).
    - Skips lines containing any word in `exclude_words`.
    - Collects next `n` integers >= 1000 that are not calendar years.
    - Handles parenthesis-negation: '(' before a number makes it negative.
    Returns (list_of_raw_millions, source_line_index) or (None, -1).
    """
    label_lower = label.lower()
    exclude_words = [w.lower() for w in (exclude_words or [])]

    for i in range(start, min(end, len(lines))):
        line = lines[i]
        if skip_long_lines and len(line) > 60 and label_lower in line.lower():
            continue
        if label_lower not in line.lower():
            continue
        if exclude_words and any(w in line.lower() for w in exclude_words):
            continue

        nums, neg = [], False
        for j in range(i, min(i + 40, len(lines))):
            l = lines[j].strip()
            if l == "(":
                neg = True;  continue
            if l == ")":
                neg = False; continue
            if re.match(r"^[\d,]+$", l):
                v = int(l.replace(",", ""))
                if v >= 1000 and not _is_year(v):
                    nums.append(-v if neg else v)
                    neg = False
                    if len(nums) == n:
                        return nums, i
        if len(nums) >= n:
            return nums[:n], i

    return None, -1


def _to_billions(values: list) -> list:
    return [round(v / 1000, 3) for v in values]


def _order3(values: list, order: str) -> list:
    """
    Normalise a 3-year list to [FY2023, FY2024, FY2025].
    newest_first filing: raw = [FY2025, FY2024, FY2023] → reverse.
    oldest_first filing: raw = [FY2023, FY2024, FY2025] → keep.
    """
    return list(reversed(values)) if order == "newest_first" else list(values)


def _order2(values: list, order: str) -> list:
    """
    Normalise a 2-year balance-sheet list to [FY2024, FY2025].
    newest_first: raw = [FY2025, FY2024] → reverse.
    oldest_first: raw = [FY2024, FY2025] → keep.
    After this call, result[0] = FY2024, result[1] = FY2025.
    """
    return list(reversed(values)) if order == "newest_first" else list(values)


# ── Main extraction function ───────────────────────────────────────────────────

def extract(company: str) -> dict:
    """
    Extract all key financial figures for `company` from its HTM filing.
    Returns a dict compatible with the FINANCIAL_DATA structure used by the app,
    plus a 'citations' sub-dict mapping every field to its source label + line number.
    FY2023 balance-sheet figures are None (not present in FY2025 10-K filings).
    """
    cfg   = CONFIGS[company]
    path  = cfg["filepath"]
    order = cfg["order"]

    if not os.path.exists(path):
        return {"error": f"Filing not found: {path}"}

    lines     = load_lines(path)
    sec       = detect_sections(company, lines)   # dynamic — no hardcoded line numbers
    citations = {}
    data      = {"years": cfg["years"], "fiscal_year_end": cfg["fiscal_year_end"]}

    # ── Income statement (3 years) ────────────────────────────────────────────
    s, e = sec["income"]
    for field, (label, excl) in cfg["income_labels"].items():
        vals, idx = find_values(lines, label, 3, s, e, exclude_words=excl)
        if vals:
            data[field]      = _to_billions(_order3(vals, order))
            citations[field] = f"{os.path.basename(path)} — '{label}' (line {idx})"
        else:
            data[field]      = [None, None, None]
            citations[field] = f"NOT FOUND: '{label}' in lines {s}–{e}"

    # Google: gross_profit = revenue − cost_of_revenues (not a direct label)
    if company == "Google":
        rev  = data.get("revenue",        [None]*3)
        cost = data.get("cost_of_revenues",[None]*3)
        if all(r is not None and c is not None for r, c in zip(rev, cost)):
            data["gross_profit"] = [round(r - c, 3) for r, c in zip(rev, cost)]
            citations["gross_profit"] = (
                f"Computed: Revenue − Cost of revenues  "
                f"(lines {citations.get('revenue','?')} · {citations.get('cost_of_revenues','?')})"
            )
        else:
            data["gross_profit"] = [None]*3
        del data["cost_of_revenues"]

    # ── Balance sheet (FY2024 + FY2025 only; FY2023 = None) ──────────────────
    s, e = sec["balance"]

    if company == "Apple":
        # Total assets
        vals, idx = find_values(lines, "Total assets", 2, s, e)
        if vals:
            fy24, fy25 = _order2(vals, order)          # always [FY2024, FY2025] after _order2
            data["total_assets"] = [None, round(fy24/1000,3), round(fy25/1000,3)]
            citations["total_assets"] = f"{os.path.basename(path)} — 'Total assets' (line {idx})"
        else:
            data["total_assets"] = [None, None, None]
            citations["total_assets"] = "NOT FOUND: 'Total assets'"

        # Term debt: two occurrences — current + non-current; sum them per year
        cur_vals,  cur_idx  = find_values(lines, "Term debt", 2, s, e)
        noncur_vals, nc_idx = (find_values(lines, "Term debt", 2, cur_idx + 1, e)
                               if cur_idx >= 0 else (None, -1))
        if cur_vals and noncur_vals:
            cur24,  cur25  = _order2(cur_vals,    order)
            nc24,   nc25   = _order2(noncur_vals, order)
            data["total_debt"] = [None,
                                  round((cur24 + nc24) / 1000, 3),   # FY2024
                                  round((cur25 + nc25) / 1000, 3)]   # FY2025
            citations["total_debt"] = (
                f"{os.path.basename(path)} — 'Term debt' current (line {cur_idx}) "
                f"+ non-current (line {nc_idx}), summed"
            )
        else:
            data["total_debt"] = [None, None, None]
            citations["total_debt"] = "NOT FOUND: Apple term debt"

    else:
        raw = {}
        for field, (label, excl) in BALANCE_LABELS[company].items():
            vals, idx = find_values(lines, label, 2, s, e, exclude_words=excl)
            if vals:
                fy24, fy25 = _order2(vals, order)
                raw[field] = (fy24, fy25, idx)
            else:
                raw[field] = (None, None, -1)

        # Microsoft: total_debt = lt_debt + current_lt_debt
        if company == "Microsoft" and "lt_debt" in raw and "current_lt_debt" in raw:
            lt24,  lt25,  lt_idx  = raw["lt_debt"]
            cur24, cur25, cur_idx = raw["current_lt_debt"]
            if lt24 and cur24:
                data["total_debt"] = [None,
                                      round((lt24 + cur24) / 1000, 3),
                                      round((lt25 + cur25) / 1000, 3)]
                citations["total_debt"] = (
                    f"{os.path.basename(path)} — 'Long-term debt' (line {lt_idx}) "
                    f"+ 'Current portion of long-term debt' (line {cur_idx}), summed"
                )
            raw.pop("lt_debt");   raw.pop("current_lt_debt")

        for field, (fy24, fy25, idx) in raw.items():
            if field in ("lt_debt", "current_lt_debt"):
                continue
            if fy24 is not None:
                data[field]      = [None, round(fy24/1000,3), round(fy25/1000,3)]
                citations[field] = f"{os.path.basename(path)} — '{BALANCE_LABELS[company][field][0]}' (line {idx})"
            else:
                data[field]      = [None, None, None]
                citations[field] = f"NOT FOUND: '{BALANCE_LABELS[company][field][0]}' in lines {s}–{e}"

    # ── Cash flow statement (3 years) ─────────────────────────────────────────
    s, e = sec["cashflow"]
    for field, (label, excl) in cfg["cashflow_labels"].items():
        vals, idx = find_values(lines, label, 3, s, e, exclude_words=excl)
        if vals:
            ordered = _order3([abs(v) for v in vals], order)   # capex stored positive
            data[field]      = _to_billions(ordered)
            citations[field] = f"{os.path.basename(path)} — '{label}' (line {idx})"
        else:
            data[field]      = [None, None, None]
            citations[field] = f"NOT FOUND: '{label}' in lines {s}–{e}"

    # ── Equity (balance sheet, FY2024 + FY2025) ───────────────────────────────
    s, e = sec["balance"]
    eq_label, eq_excl = BALANCE_LABELS[company]["equity"]
    eq_vals, eq_idx = find_values(lines, eq_label, 2, s, e, exclude_words=eq_excl)
    if eq_vals:
        fy24, fy25 = _order2(eq_vals, order)
        data["equity"]      = [None, round(fy24/1000, 3), round(fy25/1000, 3)]
        citations["equity"] = f"{os.path.basename(path)} — '{eq_label}' (line {eq_idx})"
    else:
        data["equity"]      = [None, None, None]
        citations["equity"] = f"NOT FOUND: '{eq_label}'"

    # ── Conflict detection ─────────────────────────────────────────────────────
    data["conflicts"] = detect_conflicts(company, data)

    # ── Source strings for UI display ─────────────────────────────────────────
    data["citations"]       = citations
    data["source_income"]   = f"{os.path.basename(path)} — income statement (lines {sec['income'][0]}–{sec['income'][1]})"
    data["source_balance"]  = f"{os.path.basename(path)} — balance sheet (lines {sec['balance'][0]}–{sec['balance'][1]})"
    data["source_cashflow"] = f"{os.path.basename(path)} — cash flow statement (lines {sec['cashflow'][0]}–{sec['cashflow'][1]})"

    return data


# ── Conflict detection ─────────────────────────────────────────────────────────

# Calendar periods that each company's "FY2025" actually covers.
FISCAL_PERIODS = {
    "Apple":     "Oct 2024 – Sep 2025",
    "Microsoft": "Jul 2024 – Jun 2025",
    "Google":    "Jan 2025 – Dec 2025",
}


def detect_conflicts(company: str, data: dict) -> list:
    """
    Surface data conflicts and comparability warnings for this company's filing.
    Returns a list of dicts, each with 'severity', 'title', and 'detail'.
    """
    conflicts = []

    # 1. Fiscal year period mismatch (always relevant in cross-company comparison)
    period = FISCAL_PERIODS.get(company, "")
    other_periods = {c: p for c, p in FISCAL_PERIODS.items() if c != company}
    conflicts.append({
        "severity": "warning",
        "title":    f"Fiscal year period: {period}",
        "detail":   (
            f"{company} FY2025 covers {period}. "
            f"Comparing with {' and '.join(other_periods.keys())} "
            f"({', '.join(other_periods.values())}) means 'FY2025' is not the same "
            f"calendar period across companies — up to 9 months of offset."
        ),
    })

    # 2. Non-operating items: flag when net income deviates materially from operating income
    ni = (data.get("net_income") or [None]*3)[-1]
    oi = (data.get("operating_income") or [None]*3)[-1]
    if ni is not None and oi is not None and oi != 0:
        diff = round(ni - oi, 2)
        pct  = round(abs(diff) / oi * 100, 1)
        if pct > 10:
            conflicts.append({
                "severity": "conflict",
                "title":    f"Net income vs operating income diverge by {pct}%",
                "detail":   (
                    f"FY2025: Operating income = ${oi}B, Net income = ${ni}B "
                    f"(difference: ${diff:+.2f}B). Large non-operating items "
                    f"(investment gains, interest, tax adjustments) make net income "
                    f"not directly comparable to peers without adjustment."
                ),
            })

    # 3. Balance sheet coverage: FY2023 missing from these filings
    assets = data.get("total_assets") or []
    if assets and assets[0] is None:
        conflicts.append({
            "severity": "warning",
            "title":    "FY2023 balance sheet not available in this filing",
            "detail":   (
                "The FY2025 10-K balance sheet covers only two years (FY2024 and FY2025). "
                "FY2023 balance sheet metrics (total assets, debt, equity) are marked None. "
                "Debt-to-equity for FY2023 cannot be computed from this source."
            ),
        })

    return conflicts
